name: ecommerce
run-name: deploy
on: [push]
jobs:
  Deploy-to-heroky:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: |
          docker login -u mig99 -p xZnBcAujxRZbqH5
          docker build -t ecommerce/1.0:latest .
          docker push ecommerce/1.0:latest
