name: ecommerce
run-name: deploy
on: [push]
jobs:
  deploy:
    name: Deploy to Heroku
    runs-on: ubuntu-latest
    env:
      DOCKER_USER: ${{ secrets.CI_DOCKER_USER }}
      DOCKER_PASSWORD: ${{ secrets.CI_DOCKER_PASSWORD }}
#      HEROKU_EMAIL: ${{ secrets.HEROKU_EMAIL }}
#      HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: push to docker registry
        run: |
          cat > ~/.netrc <<EOF
            machine api.heroku.com
            login ${{ secrets.HEROKU_EMAIL }}
            password ${{ secrets.HEROKU_API_KEY }}
            machine git.heroku.com
            login ${{ secrets.HEROKU_EMAIL }}
            password ${{ secrets.HEROKU_API_KEY }}
          EOF
          heroku container:login
          docker login -u ${DOCKER_USER} -p ${DOCKER_PASSWORD}
          docker build -t ecommerce .
          docker tag ecommerce registry.heroku.com/ecommerce-jm/web
          docker push registry.heroku.com/ecommerce-jm/web
          heroku container:release web
