name: ecommerce
run-name: deploy
on: [push]
jobs:
  Deploy-to-heroku:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: |
          docker login -u mig99 -p xZnBcAujxRZbqH5
          docker build -t ecommerce .
          docker tag ecommerce mig99/ecommerce:latest
          docker push mig99/ecommerce:latest
