name: ecommerce
run-name: deploy
on: [push]
jobs:
  deploy:
    name: Deploy to Heroku
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Check out repository code
        env:
          DOCKER_USER: ${{ secrets.CI_DOCKER_USER }}
          DOCKER_PASSWORD: ${{ secrets.CI_DOCKER_PASSWORD }}

      - name: push to docker registry

        run: |
          echo $DOCKER_USER
          docker login -u ${ DOCKER_USER } -p ${ DOCKER_PASSWORD }
          docker build -t ecommerce .
          docker tag ecommerce ${DOCKER_USER}/ecommerce:latest
          docker push ${DOCKER_USER}/ecommerce:latest

      - name: push to heroku
        run: |
          heroku login -i
          condori.miguel99@hotmail.com
          aA!1234459087
          heroku container:push web -a ecommerce-jm
          heroku container:release web -a ecommerce-jm