name: ecommerce
run-name: deploy
on: [push]
jobs:
  deploy:
    name: Deploy to Heroku
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          docker_user: mig99
          docker_password: ${{ secrets.CI_docker_password }}

      - name: push to docker registry
        run: |
          echo $docker_user
          echo $docker_password
          docker login -u $docker_user -p $docker_password
          docker build -t ecommerce .
          docker tag ecommerce $docker_user/ecommerce:latest
          docker push $docker_user/ecommerce:latest

      - name: push to heroku
        run: |
          heroku login -i
          condori.miguel99@hotmail.com
          aA!1234459087
          heroku container:push web -a ecommerce-jm
          heroku container:release web -a ecommerce-jm