name: ecommerce
run-name: deploy
on: [push]
jobs:
  Deploy-to-heroky:
    runs-on: ubuntu-latest
    steps:
      - run: |
          cd ../../
          docker login -u ${{ secrets.CI_DOCKER_USER }} -p ${{ secrets.CI_DOCKER_PASSWORD }}
          docker build -t ecommerce/1.0:latest .
          docker push ecommerce/1.0:latest
